### ISSUE TITLE
Travis build for OpenJDK7 is broken

### ISSUE THREAD

**Issue by gtors** [kaleidos/grails-postgresql-extensions#108]
Build failed on downloading https://services.gradle.org/distributions/gradle-3.1-bin.zip

Details here: https://travis-ci.org/kaleidos/grails-postgresql-extensions/jobs/285665218

**Comment by ilopmar** [comment]
There is an open issue on Travis about this: https://github.com/travis-ci/travis-ci/issues/8574

**Comment by ilopmar** [comment]
Fixed here: https://github.com/kaleidos/grails-postgresql-extensions/commit/ab60a013bb8c5554c04422fffe1f553c308b1ef0

Travis build: https://travis-ci.org/kaleidos/grails-postgresql-extensions/builds/296857202
