### ISSUE TITLE
Would you please support hibernate 5.2 ?

### ISSUE THREAD

**Issue by abcfy2** [kaleidos/grails-postgresql-extensions#111]
Thanks to this extension. My question is that would you plan to add support hibernate 5.2 ?

**Comment by ilopmar** [comment]
There's a PR about it, but I'm not sure about its status: #110

**Comment by donbeave** [comment]
@abcfy2 I think you can close this issue and wait for merge of this PR (which include your fixes also): https://github.com/kaleidos/grails-postgresql-extensions/pull/114

**Comment by abcfy2** [comment]
OK
