### ISSUE TITLE
How to translate grails.gorm.default.mapping to application.yml file?

### ISSUE THREAD

**Issue by kevintanhongann** [kaleidos/grails-postgresql-extensions#121]
```
grails.gorm.default.mapping = {
    id generator: 'org.hibernate.id.enhanced.SequenceStyleGenerator', params: [prefer_sequence_per_entity: true]
}
```

How to translate this to be inserted in the application.yml file in Grails 3? It's not documented in the guide at all.

**Comment by ilopmar** [comment]
Not really sure about it because `id` is a method with different parameters: `generator` and `params`.
Can you please explain your use case? Why can't you use `application.groovy` for this configuration?
