### ISSUE TITLE
Support Grails 4.x

### ISSUE THREAD

**Issue by jamesdh** [kaleidos/grails-postgresql-extensions#122]
Just curious if there is any plan to release a version supporting Grails 4.x+?

**Comment by ilopmar** [comment]
I'm not using the plugin anymore and I'm pretty busy at this moment so I expect a contribution from the community that upgrades the plugin to Grails 4.x
To be honest I think the only changes required will be because of Hibernate 5.4 and not because of Grails 4.

**Comment by jamesdh** [comment]
@ilopmar I forked it and went ahead upgrading it at https://github.com/jamesdh/grails-postgresql-extensions. I'll hold off on submitting a PR until a final version of Grails 4.0 is released. If you have any other suggestions, I'm all ears!

**Comment by ilopmar** [comment]
That was fast, thank you very much. Don't worry to much about the PR, just make sure all the tests pass. I can clean it up after merge it.
