### ISSUE TITLE
PostgreSQLDialect deprecated

### ISSUE THREAD

**Issue by mdbishop** [kaleidos/grails-postgresql-extensions#55]
Just wanted to point out that (at least in Hibernate4) PostgreSQL81Dialect seems to be the base Dialect for Postgres with PostgreSQLDialect deprecated.  

Will leave it to you to decide if this has any practical effect in the medium term but just wanted to flag it.

**Comment by lmivan** [comment]
Hi!

In the `master` branch (which uses Hibernate4) we're using `PostgreSQL81Dialect` https://github.com/kaleidos/grails-postgresql-extensions/blob/master/src/java/net/kaleidos/hibernate/PostgresqlExtensionsDialect.java#L16

In the `3.x` branch we're using `PostgreSQLDialect` which I think is not deprecated for Hibernate3.
