### ISSUE TITLE
Any plan to migrate to Grails V3.x? 

### ISSUE THREAD

**Issue by saharabear** [kaleidos/grails-postgresql-extensions#60]
Hi, 

I am very glad to find grails-postgresql-extensions, it's a good project.

At the moment, Grails is upgrading to V3.x, do we have any plan to migrate to Grails V3.x?

Thanks.

**Comment by lmivan** [comment]
Hi.

I'm glad you like it. Yes, we do have plans to migrate to project to be Grails 3.x compatible but at this moment we can't commit to a date.

Regards, Iván.

**Comment by saharabear** [comment]
I send a PR, https://github.com/kaleidos/grails-postgresql-extensions/pull/61

unit test failure, but compile works.

**Comment by DanishKhakwani** [comment]
Any news? Eagerly waiting for it to work on Grails 3.

**Comment by lmivan** [comment]
I've been reviewing this PR #70 in which you can find instructions about how to use the first "snapshot" version: https://github.com/kaleidos/grails-postgresql-extensions/pull/70#issuecomment-127016350

If you give it a try, please let me now if it's working properly or you have some problems.

**Comment by mengelhart** [comment]
Thanks everyone for the effort to get a Grails 3 build out.. Just now I tested it and got the following in my console:

`ERROR org.hibernate.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: create table test_hstore (id int8 not null, version int8 not null, lucky_number int4, name varchar(255), test_attributes hstore, primary key (id))`
`ERROR org.hibernate.tool.hbm2ddl.SchemaExport - ERROR: type "hstore" does not exist
  Position: 122`
`ERROR org.hibernate.tool.hbm2ddl.SchemaExport - HHH000389: Unsuccessful: create table test_hstore_map (id int8 not null, version int8 not null, lucky_number int4, name varchar(255), test_attributes hstore, primary key (id))`
`ERROR org.hibernate.tool.hbm2ddl.SchemaExport - ERROR: type "hstore" does not exist
  Position: 126`

Not sure where to look to help debug.

**Comment by lmivan** [comment]
@mengelhart I think the problem is because you haven't created the hstore extesion. Could you please let me know if you have followed the documentation?

https://github.com/kaleidos/grails-postgresql-extensions#hstore

**Comment by mengelhart** [comment]
Sorry Ivan - I was working on a new postgres install and forgot I hadn't created the extension for it! Thanks for the heads up.

Mike.

**Comment by lmivan** [comment]
Great! If you have some questions related to the new version of the plugin, please let me know. I think I'll release the first "official" version for Grails 3 after I come back from the SpringOne.

**Comment by mengelhart** [comment]
Great!  I'm just starting a greenfield Grails 3 project and was hoping this would be at least in a testable state.. So far so good but i'll ping you if I run into anything.. Mostly going to be using JSONb in this app for a few tables.

**Comment by lmivan** [comment]
I think you shouldn't have problems. I mean, the plugin has been migrated to Grails 3 based on the last released version 4.5.0, so everything should be the same.
I'll also plan to release a new 4.6.0 with some improvements and bugs fixed and I'll add that code to the Grails 3 branch.

**Comment by mengelhart** [comment]
i see you have the 4.6.0 branch out - any chance those fixes will merge into the 5.0 snapshot?

**Comment by lmivan** [comment]
I'll have some time to spend on the plugin next week so I'm going to clean the 3.X branch, merge it into master and release the first non-snapshot version of the plugin for Grails 3. Before that I'll add all the features and fixes already included in the 4.X.X versions.

**Comment by lmivan** [comment]
Plugin migrated to Grails 3. Please check more information at #70
