### ISSUE TITLE
Where is version 3.4.0?

### ISSUE THREAD

**Issue by ocomsoft** [kaleidos/grails-postgresql-extensions#64]
As above, I am trying to use the multi-tenant-single-db with this plugin and I need to revert back to Hibernate3 but I cannot use JSONB with v3.3.0

**Comment by lmivan** [comment]
I only created the new Jsonb for Hibernate4. If you need it for Hibernate3 I think I can cherry-pick the changes to that branch and release a new version.

**Comment by ocomsoft** [comment]
I appreciate all the work you have done, Imivan. However, I would love to be able to use the plugin from the repository. It turns out it's not as easy as just cherry picking the commit... :(

**Comment by lmivan** [comment]
As you said it's not just cherry-picking the commit but the changes are pretty simpler. I wish I had more spare time but at this moment I'm very busy. Sorry...

Regards, Iván.

**Comment by lmivan** [comment]
Backported from 4.X during GR8Conf Hackergarten and published in 3.4.0
