### ISSUE TITLE
NullPointerException when Json/Jsonb value is null in database

### ISSUE THREAD

**Issue by eamon316** [kaleidos/grails-postgresql-extensions#76]
```
java.lang.NullPointerException
	at net.kaleidos.hibernate.usertype.JsonMapType.nullSafeGet(JsonMapType.java:50)
	at org.hibernate.type.CustomType.nullSafeGet(CustomType.java:127)
```

This occurs when a value in Json/Jsonb column is null as `((PGobject)rs.getObject(names[0]))` returns null. `.getValue()` is then called on null value.

I will submit a pull request with updated tests

**Comment by lmivan** [comment]
Thank you! Published in 4.6.1
