### ISSUE TITLE
JsonMapType mapping does not work

### ISSUE THREAD

**Issue by bobbywarner** [kaleidos/grails-postgresql-extensions#80]
It appears there is an issue with the `JsonMapType`.  I have used this with Grails 2 successfully many time, but on my first attempt using this data type in a Grails 3.0.9 app, it fails with a mapping error.

```
No Dialect mapping for JDBC type: 90021
```

Here is a sample project that replicates the issue: 
https://github.com/bobbywarner/postgresql-extensions-testapp

There is one domain class with one attribute of type `JsonMapType`.  Please see the readme for SQL to setup a sample database that matches what's configured for the datasource.

**Comment by ilopmar** [comment]
It seems that there was a problem with the configuration of the dialect.

**Comment by ilopmar** [comment]
For further reference: https://github.com/kaleidos/grails-postgresql-extensions#configuration
