### ISSUE TITLE
Equality JsonMapType

### ISSUE THREAD

**Issue by igilfanov** [kaleidos/grails-postgresql-extensions#86]
Checking Map values for equality should be revised.

http://stackoverflow.com/questions/4082416/equality-between-2-hashmap

**Comment by ilopmar** [comment]
Thanks for submitting the issue.

Could you be please more specific about the problem? Does it means that this https://github.com/kaleidos/grails-postgresql-extensions/blob/master/src/main/groovy/net/kaleidos/hibernate/usertype/JsonMapType.java#L40 should be done in a different way?

Could you send me an example of what's happending?

Regards, Iván.

**Comment by igilfanov** [comment]
It does not update value of the field

**Comment by ilopmar** [comment]
Could you create an sample project that reproduces the issue and push it to github?

**Comment by igilfanov** [comment]
Not today, but I'll try. Thank you

**Comment by ilopmar** [comment]
Perfect. That way I'll be able to reproduce it and fix it.

**Comment by igilfanov** [comment]
https://github.com/igilfanov/jsonbupdate

**Comment by igilfanov** [comment]
I should have used beforeValidate
