### ISSUE TITLE
add support for uuid datatype

### ISSUE THREAD

**Issue by edwardotis** [kaleidos/grails-postgresql-extensions#89]
Hi,

 Can you add support for 
java.util.UUID to postgres uuid data type?
http://www.postgresql.org/docs/9.4/static/datatype-uuid.html

Thanks

**Comment by edwardotis** [comment]
Nevermind, I see that putting this in Config.groovy in grails 2.5.x does the trick:

grails.gorm.default.mapping = {
    uuid generator: 'uuid2', type: 'pg-uuid'
}

**Comment by ilopmar** [comment]
Awesome, thank you very much. If you want, you can send a PR to the README.md with that information. If you do it, please make sure that you create it from this branch https://github.com/kaleidos/grails-postgresql-extensions/tree/grails-2.x because you're using Grails 2.x
