### ISSUE TITLE
Any plan of support Hibernate 5 in future?

### ISSUE THREAD

**Issue by donbeave** [kaleidos/grails-postgresql-extensions#90]

**Comment by ilopmar** [comment]
Yes, I do plan to support it, based on the migration from Hibernate 3 to Hibernate 4, I think it shouldn't be complicated. I only need to find some time to do it.
In the mean time, pull requests are welcomed :)

**Comment by erichelgeson** [comment]
Grails 3.2.x line will be hibernate 5 by default. You can still use Hibernate 4 with this plugin and GORM6 by downgrading the hibernate version http://gorm.grails.org/6.0.x/hibernate/manual/index.html#hibernateVersions

**Comment by ilopmar** [comment]
Done in PR #99 and released as a initial version on `5.0.0-RC1`
